### PR TITLE
Apply machine configs only if template files exist

### PR DESCRIPTION
**Pull request by mcornea**
Currently it's failing because there are no worker templates: error: the path "./assets/post-install/*-worker.yaml" does not exist

Also export KUBECONFIG to allow oc commands to run successfully.

### CODE REVIEW

**Comment by mcornea** [comment]
Without the exporting KUBECONFIG:

```shell
./99_post_install.sh
Logging to ./logs/99_post_install-2019-09-05-212824.log
+ source common.sh
++++ dirname common.sh
+++ cd .
+++ pwd
++ SCRIPTDIR=/home/cloud-user/install-scripts/OpenShift
+++ whoami
++ USER=cloud-user
++ '[' -z '' ']'
++ '[' -f /home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh ']'
++ echo 'Using CONFIG /home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh'
Using CONFIG /home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh
++ CONFIG=/home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh
++ source /home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh
+++ set +x
+++ INT_IF=eth1
+++ PRO_IF=eth0
++ export LIBVIRT_DEFAULT_URI=qemu:///system
++ LIBVIRT_DEFAULT_URI=qemu:///system
++ '[' cloud-user '!=' root -a /run/user/1000 == /run/user/0 ']'
++ sudo -n uptime
+++ awk -F= '/^VERSION_ID=/ { print $2 }' /etc/os-release
+++ tr -d '"'
+++ cut -f1 -d.
++ VER=8
+++ awk -F= '/^ID=/ { print $2 }' /etc/os-release
+++ tr -d '"'
++ [[ rhel != \r\h\e\l ]]
++ [[ 8 -ne 8 ]]
++ '[' 3955 = 0 ']'
+ KUBECONFIG=ocp/auth/kubeconfig
+ POSTINSTALL_ASSETS_DIR=./assets/post-install
+ IFCFG_INTERFACE=./assets/post-install/ifcfg-interface.template
+ IFCFG_BRIDGE=./assets/post-install/ifcfg-bridge.template
+ BREXT_FILE=./assets/post-install/99-brext-master.yaml
+ EXTRA_REGISTRY_FILE=./assets/post-install/99-extra-registry.yaml
+ export bridge=brext
+ bridge=brext
+ create_bridge
+ echo 'Deploying Bridge brext...'
Deploying Bridge brext...
++ oc get node -o 'custom-columns=IP:.status.addresses[0].address' --no-headers
++ head -1
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
+ FIRST_MASTER=
++ ssh -q -o StrictHostKeyChecking=no core@ 'ip r | grep default | grep -Po  '\''(?<=dev )(\S+)'\'''
+ export interface=
+ interface=
+ '[' '' == '' ']'
+ echo 'Issue detecting interface to use! Leaving...'
Issue detecting interface to use! Leaving...
+ exit 1
make[1]: Leaving directory '/home/cloud-user/install-scripts/OpenShift'
~/install-scripts
```

**Comment by sreichar** [comment]
@mcornea - Did you test this?  negative and positive?

**Comment by mcornea** [comment]
> @mcornea - Did you test this? negative and positive?

Yes, tested! 

```shell
2019-09-05 23:16:39 | ./99_post_install.sh
2019-09-05 23:16:39 | Logging to ./logs/99_post_install-2019-09-05-231639.log
2019-09-05 23:16:39 | + source common.sh
2019-09-05 23:16:39 | ++++ dirname common.sh
2019-09-05 23:16:39 | +++ cd .
2019-09-05 23:16:39 | +++ pwd
2019-09-05 23:16:39 | ++ SCRIPTDIR=/home/cloud-user/install-scripts/OpenShift
2019-09-05 23:16:39 | +++ whoami
2019-09-05 23:16:39 | ++ USER=cloud-user
2019-09-05 23:16:39 | ++ '[' -z '' ']'
2019-09-05 23:16:39 | ++ '[' -f /home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh ']'
2019-09-05 23:16:39 | ++ echo 'Using CONFIG /home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh'
2019-09-05 23:16:39 | Using CONFIG /home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh
2019-09-05 23:16:39 | ++ CONFIG=/home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh
2019-09-05 23:16:39 | ++ source /home/cloud-user/install-scripts/OpenShift/config_cloud-user.sh
2019-09-05 23:16:39 | +++ set +x
2019-09-05 23:16:39 | +++ INT_IF=eth1
2019-09-05 23:16:39 | +++ PRO_IF=eth0
2019-09-05 23:16:39 | ++ export LIBVIRT_DEFAULT_URI=qemu:///system
2019-09-05 23:16:39 | ++ LIBVIRT_DEFAULT_URI=qemu:///system
2019-09-05 23:16:39 | ++ '[' cloud-user '!=' root -a /run/user/1000 == /run/user/0 ']'
2019-09-05 23:16:39 | ++ sudo -n uptime
2019-09-05 23:16:39 | +++ awk -F= '/^VERSION_ID=/ { print $2 }' /etc/os-release
2019-09-05 23:16:39 | +++ tr -d '"'
2019-09-05 23:16:39 | +++ cut -f1 -d.
2019-09-05 23:16:39 | ++ VER=8
2019-09-05 23:16:39 | +++ awk -F= '/^ID=/ { print $2 }' /etc/os-release
2019-09-05 23:16:39 | +++ tr -d '"'
2019-09-05 23:16:39 | ++ [[ rhel != \r\h\e\l ]]
2019-09-05 23:16:39 | ++ [[ 8 -ne 8 ]]
2019-09-05 23:16:39 | ++ '[' 3955 = 0 ']'
2019-09-05 23:16:39 | + export KUBECONFIG=ocp/auth/kubeconfig
2019-09-05 23:16:39 | + KUBECONFIG=ocp/auth/kubeconfig
2019-09-05 23:16:39 | + POSTINSTALL_ASSETS_DIR=./assets/post-install
2019-09-05 23:16:39 | + IFCFG_INTERFACE=./assets/post-install/ifcfg-interface.template
2019-09-05 23:16:39 | + IFCFG_BRIDGE=./assets/post-install/ifcfg-bridge.template
2019-09-05 23:16:39 | + BREXT_FILE=./assets/post-install/99-brext-master.yaml
2019-09-05 23:16:39 | + export bridge=brext
2019-09-05 23:16:39 | + bridge=brext
2019-09-05 23:16:39 | + create_bridge
2019-09-05 23:16:39 | + echo 'Deploying Bridge brext...'
2019-09-05 23:16:39 | Deploying Bridge brext...
2019-09-05 23:16:39 | ++ oc get node -o 'custom-columns=IP:.status.addresses[0].address' --no-headers
2019-09-05 23:16:39 | ++ head -1
2019-09-05 23:16:39 | + FIRST_MASTER=192.168.123.149
2019-09-05 23:16:39 | ++ ssh -q -o StrictHostKeyChecking=no core@192.168.123.149 'ip r | grep default | grep -Po  '\''(?<=dev )(\S+)'\'''
2019-09-05 23:16:40 | + export interface=ens4
2019-09-05 23:16:40 | + interface=ens4
2019-09-05 23:16:40 | + '[' ens4 == '' ']'
2019-09-05 23:16:40 | + '[' ens4 '!=' brext ']'
2019-09-05 23:16:40 | + echo 'Using interface ens4'
2019-09-05 23:16:40 | Using interface ens4
2019-09-05 23:16:40 | ++ envsubst
2019-09-05 23:16:40 | ++ base64 -w0
2019-09-05 23:16:40 | + export interface_content=REVWSUNFPWVuczQKQlJJREdFPWJyZXh0Ck9OQk9PVD15ZXMKTk1fQ09OVFJPTExFRD15ZXMKQk9PVFBST1RPPW5vbmUK
2019-09-05 23:16:40 | + interface_content=REVWSUNFPWVuczQKQlJJREdFPWJyZXh0Ck9OQk9PVD15ZXMKTk1fQ09OVFJPTExFRD15ZXMKQk9PVFBST1RPPW5vbmUK
2019-09-05 23:16:40 | ++ envsubst
2019-09-05 23:16:40 | ++ base64 -w0
2019-09-05 23:16:40 | + export bridge_content=REVWSUNFPWJyZXh0Ck5BTUU9YnJleHQKVFlQRT1CcmlkZ2UKT05CT09UPXllcwpOTV9DT05UUk9MTEVEPXllcwpCT09UUFJPVE89ZGhjcApCUklER0lOR19PUFRTPXZsYW5fZmlsdGVyaW5nPTEKQlJJREdFX1ZMQU5TPSIxIHB2aWQgdW50YWdnZWQsMjAsMzAwLTQwMCB1bnRhZ2dlZCIK
2019-09-05 23:16:40 | + bridge_content=REVWSUNFPWJyZXh0Ck5BTUU9YnJleHQKVFlQRT1CcmlkZ2UKT05CT09UPXllcwpOTV9DT05UUk9MTEVEPXllcwpCT09UUFJPVE89ZGhjcApCUklER0lOR19PUFRTPXZsYW5fZmlsdGVyaW5nPTEKQlJJREdFX1ZMQU5TPSIxIHB2aWQgdW50YWdnZWQsMjAsMzAwLTQwMCB1bnRhZ2dlZCIK
2019-09-05 23:16:40 | + envsubst
2019-09-05 23:16:40 | + echo 'Done creating bridge definition'
2019-09-05 23:16:40 | Done creating bridge definition
2019-09-05 23:16:40 | + apply_mc
2019-09-05 23:16:40 | + for node_type in master worker
2019-09-05 23:16:40 | ++ find ./assets/post-install -iname '*-master.yaml' -type f
2019-09-05 23:16:40 | + test ./assets/post-install/99-brext-master.yaml
2019-09-05 23:16:40 | + oc patch --type=merge '--patch={"spec":{"paused":true}}' machineconfigpool/master
2019-09-05 23:16:40 | machineconfigpool.machineconfiguration.openshift.io/master patched
2019-09-05 23:16:40 | + echo 'Applying machine configs...'
2019-09-05 23:16:40 | Applying machine configs...
2019-09-05 23:16:40 | + oc create -f ./assets/post-install/99-brext-master.yaml
2019-09-05 23:16:40 | machineconfig.machineconfiguration.openshift.io/99-brext-master created
2019-09-05 23:16:40 | + oc patch --type=merge '--patch={"spec":{"paused":false}}' machineconfigpool/master
2019-09-05 23:16:40 | machineconfigpool.machineconfiguration.openshift.io/master patched
2019-09-05 23:16:40 | + echo 'Rebooting nodes...'
2019-09-05 23:16:40 | Rebooting nodes...
2019-09-05 23:16:40 | + sleep 30
2019-09-05 23:17:10 | + oc wait mcp/master --for condition=updated --timeout 600s
2019-09-05 23:27:07 | The connection to the server api.rhhi-virt-cluster.qe.lab.redhat.com:6443 was refused - did you specify the right host or port?
2019-09-05 23:27:07 | + sleep 1
2019-09-05 23:27:08 | + oc wait mcp/master --for condition=updated --timeout 600s
2019-09-05 23:39:29 | error: timed out waiting for the condition on machineconfigpools/master
2019-09-05 23:39:29 | + sleep 1
2019-09-05 23:39:30 | + oc wait mcp/master --for condition=updated --timeout 600s
2019-09-05 23:51:15 | error: timed out waiting for the condition on machineconfigpools/master
2019-09-05 23:51:15 | + sleep 1
2019-09-05 23:51:16 | + oc wait mcp/master --for condition=updated --timeout 600s
2019-09-05 23:51:38 | The connection to the server api.rhhi-virt-cluster.qe.lab.redhat.com:6443 was refused - did you specify the right host or port?
2019-09-05 23:51:38 | + sleep 1
2019-09-05 23:51:39 | + oc wait mcp/master --for condition=updated --timeout 600s
2019-09-05 23:54:09 | machineconfigpool.machineconfiguration.openshift.io/master condition met
2019-09-05 23:54:09 | + for node_type in master worker
2019-09-05 23:54:09 | ++ find ./assets/post-install -iname '*-worker.yaml' -type f
2019-09-05 23:54:09 | + test
2019-09-05 23:54:09 | Done! 
2019-09-05 23:54:09 | make[1]: Leaving directory '/home/cloud-user/install-scripts/OpenShift'
2019-09-05 23:54:09 | ~/install-scripts
```

**Pull request merged**
