### PR TITLE
cnv: add option to specify quay token directly

### PR DESCRIPTION
**Pull request by lukas-bednar**
In case user already has a token, there is no need to specify username
and password to get a token.

Signed-off-by: Lukas Bednar <lbednar@redhat.com>

### CODE REVIEW

**Comment by sreichar** [comment]
@lukas-bednar while this looks good, have you tested it?

**Comment by lukas-bednar** [comment]
I didn't get to it today, it is first thing on my list tomorrow morning!

**Comment by lukas-bednar** [comment]
I am seeing following error, am not sure if it is related:
```
[cnv-qe-jenkins@cnv-executor-lbednar ~]$ oc describe  catalogsourceconfig.operators.coreos.com/hco-catalogsource-config
Name:         hco-catalogsource-config
Namespace:    openshift-marketplace
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"operators.coreos.com/v1","kind":"CatalogSourceConfig","metadata":{"annotations":{},"name":"hco-catalogsource-config","names...
API Version:  operators.coreos.com/v2
Kind:         CatalogSourceConfig
Metadata:
  Creation Timestamp:  2019-09-05T20:13:09Z
  Finalizers:
    finalizer.catalogsourceconfigs.operators.coreos.com
  Generation:        3
  Resource Version:  21645
  Self Link:         /apis/operators.coreos.com/v2/namespaces/openshift-marketplace/catalogsourceconfigs/hco-catalogsource-config
  UID:               9447cabb-d019-11e9-a608-fa163e915116
Spec:
  Cs Display Name:   CNV Operators
  Cs Publisher:      Red Hat
  Packages:          kubevirt-hyperconverged
  Source:            rh-osbs-operators
  Target Namespace:  openshift-marketplace
Status:
  Current Phase:
    Last Transition Time:  2019-09-05T20:13:09Z
    Last Update Time:      2019-09-05T20:13:09Z
    Phase:
      Message:  Still resolving package(s) - kubevirt-hyperconverged. Please make sure these are valid packages within the rh-osbs-operators OperatorSource.
      Name:     Configuring
Events:         <none>
```

**Comment by e-minguez** [comment]
I'd say to include a brief description on how to create the QUAY token

**Comment by e-minguez** [comment]
I'm not sure about the scripts intended to be interactive. I'd say to better verify the variables exists (either token or user&pass) or fail instead.

**Comment by lukas-bednar** [comment]
> I'm not sure about the scripts intended to be interactive. I'd say to better verify the variables exists (either token or user&pass) or fail instead.

I agree with this statement, I will do so.

**Comment by sreichar** [comment]
@lukas-bednar 

With the merge of PR #141,   I don't think this merge is needed.

Please close if you agree

**Comment by lukas-bednar** [comment]
agree

**Pull request closed without merging**
