### PR TITLE
Remove bootstrap VM and some other assets

### LINKED ISSUE #52: Running `make clean` makes your host unreachable
```
$ make clean
...
+ virsh net-uuid baremetal
+ virsh net-destroy baremetal
Network baremetal destroyed

+ virsh net-undefine baremetal
Network baremetal has been undefined

+ sudo ifdown baremetal
WARN      : [ifdown] You are using 'ifdown' script provided by 'network-scripts', which are now deprecated.
WARN      : [ifdown] 'network-scripts' will be removed in one of the next major releases of RHEL.
WARN      : [ifdown] It is advised to switch to 'NetworkManager' instead - it provides 'ifup/ifdown' scripts as well.
```

As it just removes the interfaces, the network connection is lost and I cannot connect back to the host.

### PR DESCRIPTION
**Pull request by e-minguez**
Fixes #52 #71

### CODE REVIEW

**Comment by e-minguez** [comment]
I'm not sure if:

- Removing the virtual networks is useful
- Removing the `ocp/` folder is useful
- Removing the 172.22.0.2 from the `~/.ssh/known_hosts` is useful

Comments?

**Comment by sreichar** [comment]
I am of the opinion that removing hte virtual network is not useful 
Think the other two make sense

Did you look to see what @hardys  recommended - using openshift_baremetal_intaller destroy cluster?

**Comment by e-minguez** [comment]
IIRC @hardys mentioned [here](https://github.com/openshift-kni/install-scripts/issues/52#issuecomment-527915240) is there is no complete support right now for destroy cluster.

I've just executed it and:
```
$ ocp/openshift-baremetal-install destroy cluster --log-level debug --dir ocp/
DEBUG OpenShift Installer v4.2.0                   
DEBUG Built from commit 8c9abe40f7616303c03cafdc9ad612cd8fa7bd6b 
DEBUG Deleting bare metal resources                
DEBUG FIXME: delete resources!                     
DEBUG Purging asset "Terraform Variables" from disk 
DEBUG Purging asset "Kubeconfig Admin Client" from disk 
DEBUG Purging asset "Kubeadmin Password" from disk 
DEBUG Purging asset "Certificate (journal-gatewayd)" from disk 
DEBUG Purging asset "Metadata" from disk           
DEBUG Purging asset "Cluster" from disk     
```

**Comment by sreichar** [comment]
@e-minguez Just would like to confirm you tested

**Comment by e-minguez** [comment]
Can confirm I tested it. The Masters are not cleaned but that's because the destroy cluster command doesn't do it. I think this is the most clean stuff we can make right now.

**Pull request merged**
