### PR TITLE
Pause after displaying collected data

### PR DESCRIPTION
**Pull request by sreichar**
fixes 107 Once the output of preflight is displayed, get a user confirmation

### CODE REVIEW

**Comment by e-minguez** [comment]
This will break automations IIRC as they will wait until manually 'y' is pressed.

**Comment by e-minguez** [comment]
I'd say to better include the confirmation in the preflight script and add a '-y' flag in the preflight script that assume yes (like yum -y...)

**Comment by sreichar** [comment]
It breaks automation for those using the top level makefile,    

I could make another make target that doesn't  include it,

**Comment by e-minguez** [comment]
wouldn't be clean to add it to the preflight instead?

**Comment by sreichar** [comment]
Roger suggested adding a timeout to the input - will be making that change.

**Comment by sreichar** [comment]
Pushed change to timeout, so will not break automation and no changes requires.

@e-minguez if you wouldn't mind giving another review.

**Comment by e-minguez** [comment]
I still don't see the purpose of this.

I see two different use cases:

- Automate deployments/CI - There is no need to add a delay nor a confirmation
- Manual deployments - If the scripts are executed manually, the user shall be aware of the data collected as the preflight script outputs the data

If the confirmation is really necessary for any reason, I still think having a `-y` flag would be better to avoid unnecessary delays.

My 2 cents.

**Comment by sreichar** [comment]
In the proper deploytment,   you will need to copy your pull secret to the top level directory and then type make. 

However we dont' want to present to the user the discovered values (therr DHCP/DNS settings)  to make sure it is what they want.    We can verify they exists, but can not verify they are what they expected.   This leaves the output on the screen for 30 second at most instead of just blowing past it.

**Comment by sreichar** [comment]
Closing in preference to PR #126

**Pull request closed without merging**
