### PR TITLE
Add CNV 2.1 to install scripts

### PR DESCRIPTION
**Pull request by rthallisey**
We'll start with installing CNV 2.1 from brew for
Dev and QE.  When CNV 2.1 gets pushed out to prod, we'll change
the script to consume the content from prod.

### CODE REVIEW

**Comment by karmab** [comment]
ack

**Comment by karmab** [comment]
give it a try and hco-catalogsource-config deployment doesnt show up
the catalog shows the following

```
status:
  currentPhase:
    lastTransitionTime: "2019-08-28T12:13:29Z"
    lastUpdateTime: "2019-08-28T12:13:30Z"
    phase:
      message: Still resolving package(s) - kubevirt-hyperconverged. Please make sure
        these are valid packages within the rh-osbs-operators OperatorSource.
      name: Configuring
```

**Comment by e-minguez** [comment]
My PR #28 is pending and if an insecure registry is required it can be applied there...

**Comment by karmab** [comment]
> ```shell
> oc get packagemanifest -n openshift-cnv
> oc get csc -n openshift-marketplace
> 
> oc get operatorsource rh-osbs-operators -n openshift-marketplace
> oc get catalogsource --all-namespaces
> oc get pods -n openshift-marketplace
> ```

NAME                                        CATALOG               AGE
anchore-engine                              Certified Operators   3h35m
appdynamics-operator                        Certified Operators   3h35m
aqua-certified                              Certified Operators   3h35m
cic-operator                                Certified Operators   3h35m
couchbase-enterprise-certified              Certified Operators   3h35m
cpx-cic-operator                            Certified Operators   3h35m
crunchy-postgres-operator                   Certified Operators   3h35m
federatorai-certified                       Certified Operators   3h35m
hazelcast-enterprise-certified              Certified Operators   3h35m
insightedge-operator                        Certified Operators   3h35m
instana-agent                               Certified Operators   3h35m
joget-openshift-operator                    Certified Operators   3h35m
kong                                        Certified Operators   3h35m
kubeturbo-certified                         Certified Operators   3h35m
mariadb                                     Certified Operators   3h35m
memql-certified                             Certified Operators   3h35m
mongodb-enterprise                          Certified Operators   3h35m
newrelic-infrastructure                     Certified Operators   3h35m
nuodb-ce-certified                          Certified Operators   3h35m
oneagent-certified                          Certified Operators   3h35m
openunison-ocp-certified                    Certified Operators   3h35m
orca                                        Certified Operators   3h35m
percona-server-mongodb-operator-certified   Certified Operators   3h35m
percona-xtradb-cluster-operator-certified   Certified Operators   3h35m
planetscale-certified                       Certified Operators   3h35m
portworx-certified                          Certified Operators   3h35m
presto-operator                             Certified Operators   3h35m
robin-operator                              Certified Operators   3h35m
seldon-operator-certified                   Certified Operators   3h35m
sematext                                    Certified Operators   3h35m
storageos                                   Certified Operators   3h35m
synopsys-certified                          Certified Operators   3h35m
sysdig-certified                            Certified Operators   3h35m
t8c-certified                               Certified Operators   3h35m
tidb-operator-certified                     Certified Operators   3h35m
twistlock-certified                         Certified Operators   3h35m
akka-cluster-operator                       Community Operators   3h35m
apicurito                                   Community Operators   3h35m
appsody-community-operator                  Community Operators   3h35m
aqua                                        Community Operators   3h35m
atlasmap-operator                           Community Operators   3h35m
awss3-operator-registry                     Community Operators   3h35m
camel-k                                     Community Operators   3h35m
cert-utils-operator                         Community Operators   3h35m
cockroachdb                                 Community Operators   3h35m
descheduler                                 Community Operators   3h35m
eclipse-che                                 Community Operators   3h35m
enmasse                                     Community Operators   3h35m
esindex-operator                            Community Operators   3h35m
etcd                                        Community Operators   3h35m
event-streams-topic                         Community Operators   3h35m
federation                                  Community Operators   3h35m
federatorai                                 Community Operators   3h35m
grafana-operator                            Community Operators   3h35m
hawtio-operator                             Community Operators   3h35m
hazelcast-enterprise                        Community Operators   3h35m
hco-operatorhub                             Community Operators   3h35m
ibmcloud-operator                           Community Operators   3h35m
infinispan                                  Community Operators   3h35m
iot-simulator                               Community Operators   3h35m
jaeger                                      Community Operators   3h35m
kiali                                       Community Operators   3h35m
knative-camel-operator                      Community Operators   3h35m
knative-eventing-operator                   Community Operators   3h35m
knative-kafka-operator                      Community Operators   3h35m
knative-serving-operator                    Community Operators   3h35m
kubefed-operator                            Community Operators   3h35m
kubeturbo                                   Community Operators   3h35m
metering                                    Community Operators   3h35m
microcks                                    Community Operators   3h35m
microsegmentation-operator                  Community Operators   3h35m
myvirtualdirectory                          Community Operators   3h35m
namespace-configuration-operator            Community Operators   3h35m
node-network-operator                       Community Operators   3h35m
node-problem-detector                       Community Operators   3h35m
open-liberty                                Community Operators   3h35m
opendatahub-operator                        Community Operators   3h35m
openebs                                     Community Operators   3h35m
openshift-pipelines-operator                Community Operators   3h35m
opsmx-spinnaker-operator                    Community Operators   3h35m
planetscale                                 Community Operators   3h35m
postgresql                                  Community Operators   3h35m
prometheus                                  Community Operators   3h35m
radanalytics-spark                          Community Operators   3h35m
ripsaw                                      Community Operators   3h35m
seldon-operator                             Community Operators   3h35m
spark-gcp                                   Community Operators   3h35m
spinnaker-operator                          Community Operators   3h35m
strimzi-kafka-operator                      Community Operators   3h35m
syndesis                                    Community Operators   3h35m
t8c                                         Community Operators   3h35m
triggermesh                                 Community Operators   3h35m
twistlock                                   Community Operators   3h35m
3scale-operator                             Red Hat Operators     3h35m
amq-online                                  Red Hat Operators     3h35m
amq-streams                                 Red Hat Operators     3h35m
amq7-cert-manager                           Red Hat Operators     3h35m
amq7-interconnect-operator                  Red Hat Operators     3h35m
businessautomation-operator                 Red Hat Operators     3h35m
cluster-logging                             Red Hat Operators     3h35m
codeready-workspaces                        Red Hat Operators     3h35m
datagrid                                    Red Hat Operators     3h35m
elasticsearch-operator                      Red Hat Operators     3h35m
jaeger-product                              Red Hat Operators     3h35m
kubevirt-hyperconverged                     Red Hat Operators     3h35m
openshiftansibleservicebroker               Red Hat Operators     3h35m
openshifttemplateservicebroker              Red Hat Operators     3h35m
NAME                       STATUS        MESSAGE                                                                                                                                        AGE
hco-catalogsource-config   Configuring   Still resolving package(s) - kubevirt-hyperconverged. Please make sure these are valid packages within the rh-osbs-operators OperatorSource.   81s
NAME                TYPE          ENDPOINT              REGISTRY            DISPLAYNAME         PUBLISHER   STATUS   MESSAGE                                                       AGE
rh-osbs-operators   appregistry   https://quay.io/cnr   rh-osbs-operators   rh-osbs-operators   Red Hat     Failed   The OperatorSource endpoint returned an empty manifest list   2m13s
NAMESPACE               NAME                  DISPLAY               TYPE   PUBLISHER   AGE
openshift-marketplace   certified-operators   Certified Operators   grpc   Red Hat     3h36m
openshift-marketplace   community-operators   Community Operators   grpc   Red Hat     3h35m
openshift-marketplace   redhat-operators      Red Hat Operators     grpc   Red Hat     3h36m
NAME                                    READY   STATUS    RESTARTS   AGE
certified-operators-798659946c-z6sxk    1/1     Running   0          82m
community-operators-784c79c64b-gdxxn    1/1     Running   0          82m
marketplace-operator-7bf7c58fcc-qzjlw   1/1     Running   0          82m
redhat-operators-778f6957f7-ll98n       1/1     Running   0          82m

**Comment by karmab** [comment]
also , output from *oc get operatorsource rh-osbs-operators -n openshift-marketplace*

```
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  creationTimestamp: "2019-08-28T22:04:58Z"
  finalizers:
  - finalizer.operatorsources.operators.coreos.com
  generation: 4
  name: rh-osbs-operators
  namespace: openshift-marketplace
  resourceVersion: "75437"
  selfLink: /apis/operators.coreos.com/v1/namespaces/openshift-marketplace/operatorsources/rh-osbs-operators
  uid: dfe293e1-c9df-11e9-ade5-001a4a160186
spec:
  authorizationToken:
    secretName: quay-registry-rh-osbs-operators
  displayName: rh-osbs-operators
  endpoint: https://quay.io/cnr
  publisher: Red Hat
  registryNamespace: rh-osbs-operators
  type: appregistry
status:
  currentPhase:
    lastTransitionTime: "2019-08-28T22:04:59Z"
    lastUpdateTime: "2019-08-28T22:04:59Z"
    phase:
      message: The OperatorSource endpoint returned an empty manifest list
      name: Failed
```

**Comment by rthallisey** [comment]
@karmab can you access https://quay.io/application/rh-osbs-operators/kubevirt-hyperconverged ?  Seems like your quay account doesn't have access

**Comment by johnbieren** [comment]
> My PR #28 is pending and if an insecure registry is required it can be applied there...

My understanding is it does require the insecure registry. @nellyc can you comment? If it is needed for CNV-2.1 and none of the other pillars, I would think it should be classified as part of installing CNV-2.1, so we should look to the CNV team to add a script that will add it. But I could be wrong... maybe trusting an insecure registry is no longer needed (which would be quite nice)

**Comment by karmab** [comment]
@rthallisey with the proper quay credentials, it worked!

image

@johnbieren, it indeed requires access to an internal and insecure registry, which is something that is currently done through a post install script (launched prior to deploying cnv)

@sreichar i think this can be merged

**Comment by johnbieren** [comment]
> @rthallisey with the proper quay credentials, it worked!
> 
> image
> 
> @johnbieren, it indeed requires access to an internal and insecure registry, which is something that is currently done through a post install script (launched prior to deploying cnv)

Is the post install script in install-scripts? Or is it the one in Eduardo's PR he referenced? Or neither
> 
> @sreichar i think this can be merged

**Comment by e-minguez** [comment]
> > @rthallisey with the proper quay credentials, it worked!
> > image
> > @johnbieren, it indeed requires access to an internal and insecure registry, which is something that is currently done through a post install script (launched prior to deploying cnv)
> 
> Is the post install script in install-scripts? Or is it the one in Eduardo's PR he referenced? Or neither
> 
> > @sreichar i think this can be merged

AFAIK there is no internal/insecure registry configuration/machine-config right now into this repository

**Pull request merged**
