### PR TITLE
clean up by making generate_metal3_config a function versus a file

### PR DESCRIPTION
**Pull request by sreichar**
some cleanup  - move the generate-metal3-config script to a function in 03_create_cluster

### CODE REVIEW

**Comment by sreichar** [comment]
[test]

**Comment by johnbieren** [comment]
CI failed on CNV stage (post OCP) should be good to merge :+1:

**Comment by sreichar** [comment]
[test]  retesting after resolving conflict

**Comment by sreichar** [comment]
@rlopez133 - could you approve and merge?

**Pull request merged**
