### PR TITLE
Add logging to file for OCS installation.

### PR DESCRIPTION
**Pull request by yprokule**
/cc @e-minguez @sreichar

### CODE REVIEW

**Comment by yprokule** [comment]
[test]

**Comment by e-minguez** [comment]
It failed on the CNV part... retriggering the CI just in case.

[test]

**Comment by e-minguez** [comment]
[test]

**Comment by e-minguez** [comment]
CI is failing (@johnbieren just in case) in the CNV step. I'm assuming this change is harmless so LGTM

**Pull request merged**
