### PR TITLE
Add manifest at deploy time for creating baremetalhosts.metal3.io CRD

### PR DESCRIPTION
**Pull request by mcornea**
This is a workaround for https://github.com/openshift-kni/install-scripts/issues/55 to allow running automated tests against install scripts.

### CODE REVIEW

**Comment by dhellmann** [comment]
I don't think we want to be doing this. The machine-api-operator should be adding the CRD.

/cc @sadasu

**Comment by mcornea** [comment]
> I don't think we want to be doing this. The machine-api-operator should be adding the CRD.
> 
> /cc @sadasu

Without it deployment fails as described in https://github.com/openshift-kni/install-scripts/issues/55

**Comment by dhellmann** [comment]
> > I don't think we want to be doing this. The machine-api-operator should be adding the CRD.
> > /cc @sadasu
> 
> Without it deployment fails as described in #55

Then that is a bug, and we should fix it in the component that is failing. Fixing it here just papers over the problem.

**Comment by mcornea** [comment]
> > > I don't think we want to be doing this. The machine-api-operator should be adding the CRD.
> > > /cc @sadasu
> > 
> > 
> > Without it deployment fails as described in #55
> 
> Then that is a bug, and we should fix it in the component that is failing. Fixing it here just papers over the problem.

Agreed, that's why it's a workaround but we need a way to allow install-scripts testing to progress.

**Comment by johnbieren** [comment]
Please disregard the Stage Job check on this... I wasn't ready to turn it on yet

**Comment by russellb** [comment]
@dhellmann I guess we may be seeing different behavior with dev-scripts as the CRD is still installed there: https://github.com/openshift-metal3/dev-scripts/blob/master/assets/templates/90_metal3_baremetalhost_crd.yaml

**Comment by sreichar** [comment]
@dhellmann  - how is this different from what is being done in dev-script utils.sh generate_assets?

**Comment by sreichar** [comment]
Had a sucessfull install, potentially remove is when fixed  in the machine-api-operator

**Comment by sadasu** [comment]
The baremetal CRD is already in the MAO https://github.com/openshift/machine-api-operator/blob/master/install/0000_30_machine-api-operator_13_baremetalhost.crd.yaml.

**Comment by dhellmann** [comment]
> @dhellmann - how is this different from what is being done in dev-script utils.sh generate_assets?

It's not any different. We shouldn't need the file in dev-scripts, either. I'm working on verifying that we can remove it there right now.

**Pull request merged**
